import type { Listing, Niche } from "./types";
import { SQ_M_PER_PERSON } from "./scoring";

export const DISTRICTS = [
  "Все",
  "Медеуский",
  "Бостандыкский",
  "Алмалинский",
  "Ауэзовский",
  "Алатауский",
  "Наурызбайский",
  "Турксибский",
  "Жетысуский",
];

export const PROPERTY_TYPES = [
  "Все",
  "Общепит",
  "Офис",
  "Магазин",
  "Склад",
  "Свободное",
];

export const NICHES: Niche[] = [
  {
    id: "coffee",
    label: "Кофейня",
    icon: "☕",
    directRubric: "Кофейни, Кафе-кондитерские",
    indirectRubric: "Пекарни, чайные",
  },
  {
    id: "doner",
    label: "Донерная",
    icon: "🌯",
    directRubric: "Донерные, фастфуд",
    indirectRubric: "Пиццерии, бургерные",
  },
  {
    id: "restaurant",
    label: "Ресторан",
    icon: "🍽️",
    directRubric: "Рестораны, бары",
    indirectRubric: "Кафе, банкетные залы",
  },
];

export const LISTINGS: Listing[] = [
  {
    id: 1,
    district: "Медеуский",
    propertyType: "Общепит",
    address: "ул. Гоголя 50, угол Тулебаева",
    lat: 43.2567,
    lng: 76.9453,
    area: 200,
    price: 3000000,
    m2: 15000,
    floor: 1,
    ceilings: 3.0,
    condition: "Свежий ремонт",
    entrance: "Отдельный, с улицы",
    features: ["свет", "вода", "канализация", "отопление", "вентиляция"],
    photos: [
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=350&fit=crop&q=80",
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&h=350&fit=crop&q=80",
      "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=600&h=350&fit=crop&q=80",
    ],
    source: "krisha.kz #12847291",
    radius: {
      direct: [
        { name: "Starbucks", dist: 120, rating: 4.2, check: 3500, reviews: 890 },
        { name: "URBO Coffee", dist: 280, rating: 4.5, check: 1800, reviews: 1240, branches: 40 },
        { name: "Coffee Boom", dist: 450, rating: 4.1, check: 1500, reviews: 320 },
        { name: "Дринкит", dist: 380, rating: 4.7, check: 2000, reviews: 276 },
      ],
      indirect: [
        { name: "Paul's Bakery", dist: 200, type: "пекарня", rating: 4.3 },
        { name: "Burger King", dist: 340, type: "фастфуд", rating: 3.8 },
        { name: "KFC", dist: 510, type: "фастфуд", rating: 3.5 },
      ],
      synergy: [
        { name: "БЦ Almaty Towers", dist: 90, type: "бизнес-центр", people: "~2 000 сотрудников" },
        { name: "ТЦ Dostyk Plaza", dist: 400, type: "ТЦ", people: "~15 000 посетителей/день" },
        { name: "Отель Казахстан", dist: 350, type: "гостиница", people: "~300 номеров" },
        { name: "Казахский нац. университет", dist: 800, type: "вуз", people: "~20 000 студентов" },
      ],
      gov: [
        { name: "ЦОН Медеуского р-на", dist: 600, type: "ЦОН" },
        { name: "Налоговая инспекция", dist: 800, type: "налоговая" },
        { name: "Акимат Медеуского р-на", dist: 950, type: "акимат" },
      ],
      transport: [
        { name: "ост. Тулебаева", dist: 80, routes: ["37", "63", "121"] },
        { name: "ост. Гоголя — Тулебаева", dist: 150, routes: ["2", "65", "95"] },
        { name: "Метро «Абай»", dist: 700, routes: ["M1"] },
      ],
      housing: {
        buildings: 45,
        apartments: 3200,
        totalAreaM2: 233000,
        estPopulation: Math.round(233000 / SQ_M_PER_PERSON),
        avgApartmentM2: 72,
        radius: 1000,
      },
      pedestrian: { weekday: 12400, weekend: 8200, peakHour: 1850, source: "оценка по транспорту" },
    },
  },
  {
    id: 2,
    district: "Ауэзовский",
    propertyType: "Общепит",
    address: "ул. Жандосова 108/1 — Навои, ЖК Asyl Tas",
    lat: 43.218,
    lng: 76.8687,
    area: 138,
    price: 1490000,
    m2: 10797,
    floor: 1,
    ceilings: 3.0,
    condition: "Черновая отделка",
    entrance: "Отдельный, с улицы",
    features: ["свет", "вода", "канализация", "отопление", "видеонаблюдение"],
    photos: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=350&fit=crop&q=80",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=600&h=350&fit=crop&q=80",
    ],
    source: "krisha.kz #13001847",
    radius: {
      direct: [
        { name: "Кофейня Батыр", dist: 300, rating: 4.0, check: 1200, reviews: 89 },
        { name: "Coffee Moon", dist: 520, rating: 3.8, check: 1000, reviews: 54 },
      ],
      indirect: [
        { name: "Doner House", dist: 180, type: "донерная", rating: 4.2 },
        { name: "Paloma Pizza", dist: 400, type: "пиццерия", rating: 4.0 },
      ],
      synergy: [
        { name: "ТРЦ MEGA Almaty", dist: 2200, type: "ТЦ", people: "~40 000 посетителей/день" },
        { name: "Университет Нархоз", dist: 1800, type: "вуз", people: "~8 000 студентов" },
        { name: "ЖК Asyl Tas", dist: 0, type: "жилой комплекс", people: "~1 200 квартир" },
        { name: "Фитнес World Class", dist: 600, type: "фитнес", people: "~500 членов" },
      ],
      gov: [
        { name: "Акимат Ауэзовского р-на", dist: 1500, type: "акимат" },
        { name: "ЦОН Ауэзовского р-на", dist: 2000, type: "ЦОН" },
      ],
      transport: [
        { name: "ост. Жандосова — Навои", dist: 60, routes: ["38", "44", "131"] },
        { name: "ост. Навои", dist: 250, routes: ["63", "95"] },
      ],
      housing: {
        buildings: 62,
        apartments: 5800,
        totalAreaM2: 417000,
        estPopulation: Math.round(417000 / SQ_M_PER_PERSON),
        avgApartmentM2: 65,
        radius: 1000,
      },
      pedestrian: { weekday: 6800, weekend: 4100, peakHour: 980, source: "оценка по транспорту" },
    },
  },
  {
    id: 3,
    district: "Алмалинский",
    propertyType: "Общепит",
    address: "ул. Розыбакиева 45, угол Толе би",
    lat: 43.2551,
    lng: 76.9235,
    area: 500,
    price: 7500000,
    m2: 15000,
    floor: 1,
    ceilings: 4.0,
    condition: "Черновая отделка",
    entrance: "Отдельный",
    features: ["свет", "вода", "канализация", "отопление"],
    photos: [
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&h=350&fit=crop&q=80",
    ],
    source: "krisha.kz #12993104",
    radius: {
      direct: [
        { name: "The Ritz", dist: 200, rating: 4.6, check: 8000, reviews: 1540 },
        { name: "Del Papa", dist: 350, rating: 4.3, check: 5000, reviews: 2100 },
        { name: "ABR Restaurant", dist: 180, rating: 4.4, check: 6000, reviews: 780 },
      ],
      indirect: [
        { name: "Marrone Rosso", dist: 280, type: "кофейня", rating: 4.5 },
        { name: "Degirmen", dist: 500, type: "донерная", rating: 3.7, branches: 50 },
      ],
      synergy: [
        { name: "БЦ Нурлы Тау", dist: 600, type: "бизнес-центр", people: "~5 000 сотрудников" },
        { name: "Клиника Интертич", dist: 300, type: "медцентр", people: "~500 пациентов/день" },
      ],
      gov: [
        { name: "Управление образования", dist: 700, type: "управление" },
        { name: "Суд Алмалинского р-на", dist: 900, type: "суд" },
      ],
      transport: [
        { name: "ост. Розыбакиева — Толе би", dist: 40, routes: ["2", "63", "95"] },
        { name: "ост. Толе би", dist: 200, routes: ["65", "121"] },
        { name: "Метро «Байконыр»", dist: 900, routes: ["M1"] },
      ],
      housing: {
        buildings: 38,
        apartments: 2800,
        totalAreaM2: 198000,
        estPopulation: Math.round(198000 / SQ_M_PER_PERSON),
        avgApartmentM2: 78,
        radius: 1000,
      },
      pedestrian: { weekday: 9600, weekend: 6400, peakHour: 1420, source: "оценка по транспорту" },
    },
  },
  {
    id: 4,
    district: "Наурызбайский",
    propertyType: "Свободное",
    address: "мкр Калкаман-2, ул. Актамберды жырау",
    lat: 43.285,
    lng: 76.82,
    area: 180,
    price: 540000,
    m2: 3000,
    floor: 1,
    ceilings: 3.0,
    condition: "Свежий ремонт",
    entrance: "Отдельный",
    features: ["свет", "вода", "газ", "канализация"],
    photos: [
      "https://images.unsplash.com/photo-1564069114553-7215e1ff1890?w=600&h=350&fit=crop&q=80",
    ],
    source: "krisha.kz #12788430",
    radius: {
      direct: [{ name: "Чайхана у дороги", dist: 400, rating: 3.5, check: 2000, reviews: 42 }],
      indirect: [{ name: "Магазин Анвар", dist: 150, type: "продукты", rating: 3.2 }],
      synergy: [
        { name: "Рынок Калкаман", dist: 500, type: "рынок", people: "~3 000 посетителей/день" },
        { name: "Школа №156", dist: 300, type: "школа", people: "~800 учеников" },
      ],
      gov: [{ name: "Акимат мкр Калкаман", dist: 800, type: "акимат" }],
      transport: [{ name: "ост. Калкаман-2", dist: 120, routes: ["44", "131"] }],
      housing: {
        buildings: 85,
        apartments: 4200,
        totalAreaM2: 315000,
        estPopulation: Math.round(315000 / SQ_M_PER_PERSON),
        avgApartmentM2: 58,
        radius: 1000,
      },
      pedestrian: { weekday: 2800, weekend: 1900, peakHour: 420, source: "оценка по транспорту" },
    },
  },
  {
    id: 5,
    district: "Бостандыкский",
    propertyType: "Общепит",
    address: "у ТРЦ МЕГА, ЖК R-House, 2 этаж",
    lat: 43.229,
    lng: 76.901,
    area: 183,
    price: 2745000,
    m2: 15000,
    floor: 2,
    ceilings: 5.8,
    condition: "Свежий ремонт",
    entrance: "Отдельный",
    features: ["свет", "отопление", "пожарная сигнализация"],
    photos: [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=350&fit=crop&q=80",
      "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600&h=350&fit=crop&q=80",
    ],
    source: "krisha.kz #13102553",
    radius: {
      direct: [
        { name: "Coffeedelia", dist: 250, rating: 4.6, check: 3000, reviews: 920 },
        { name: "DoubleB", dist: 400, rating: 4.4, check: 2500, reviews: 540 },
        { name: "URBO Coffee", dist: 600, rating: 4.5, check: 1800, reviews: 380, branches: 40 },
      ],
      indirect: [
        { name: "Dodo Pizza", dist: 300, type: "пиццерия", rating: 4.3 },
        { name: "DURUM", dist: 500, type: "донерная", rating: 4.8, branches: 25 },
      ],
      synergy: [
        { name: "ТРЦ MEGA Almaty", dist: 200, type: "ТЦ", people: "~40 000/день" },
        { name: "MEGA Park", dist: 400, type: "ТЦ", people: "~20 000/день" },
        { name: "Кинотеатр Kinopark", dist: 250, type: "кинотеатр", people: "~3 000/день" },
      ],
      gov: [{ name: "ЦОН Бостандыкского р-на", dist: 1800, type: "ЦОН" }],
      transport: [
        { name: "ост. МЕГА", dist: 100, routes: ["12", "37", "65", "95"] },
        { name: "ост. Розыбакиева", dist: 350, routes: ["2", "38"] },
      ],
      housing: {
        buildings: 30,
        apartments: 2400,
        totalAreaM2: 180000,
        estPopulation: Math.round(180000 / SQ_M_PER_PERSON),
        avgApartmentM2: 75,
        radius: 1000,
      },
      pedestrian: { weekday: 18500, weekend: 24000, peakHour: 3200, source: "оценка по ТЦ-трафику" },
    },
  },
];
